### ISSUE TITLE
Build in Win against O 4.99 failed.

### ISSUE THREAD

**Issue by Hakansv** [seandepagnier/weather_routing_pi#231]
Hi.
I got the following errors. Anything I've missed?
6>   Creating library C:/Builds/OCPN/weather_routing_pi/build/Release/weather_routing_pi.lib and object C:/Builds/OCPN/weather_routing_pi/build/Release/weather_routing_pi.exp
6>zuFile.obj : error LNK2019: unresolved external symbol _gzopen referenced in function _zu_open
6>zuFile.obj : error LNK2019: unresolved external symbol _gzread referenced in function _zu_read
6>zuFile.obj : error LNK2019: unresolved external symbol _gzgets referenced in function _zu_gets
6>zuFile.obj : error LNK2019: unresolved external symbol _gzseek referenced in function _zu_seek
6>zuFile.obj : error LNK2019: unresolved external symbol _gztell referenced in function _zu_seek
6>zuFile.obj : error LNK2019: unresolved external symbol _gzclose referenced in function _zu_can_read_file
6>C:\Builds\OCPN\weather_routing_pi\build\Release\weather_routing_pi.dll : fatal error LNK1120: 6 unresolved externals

**Comment by rgleason** [comment]
Hakan

It seems to be building now, after Did-g's pr 
Commits on Jan 7, 2019
  Merge pull request seandepagnier#234 from did-g/json_mingw  Json and mingw
https://github.com/rgleason/weather_routing_pi/commit/a5e239501e50ed7710bab304e1a64021dbbfd45a

With a few warnings.
```
Build succeeded.
"C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\ALL_BUILD.vcxproj
" (default target) (1) ->
"C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_p
i.vcxproj" (default target) (4) ->
(ClCompile target) ->
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\SettingsDialog.cpp
(140): warning C4800: 'long' : forcing value to bool 'true' or 'false' (perform
ance warning) [C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\wea
ther_routing_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\BoatDialog.cpp(103
6): warning C4800: 'int' : forcing value to bool 'true' or 'false' (performance
 warning) [C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather
_routing_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\Polar.cpp(840): wa
rning C4305: '=' : truncation from 'double' to 'float' [C:\Users\Frederick\Docu
ments\GitHub\weather_routing_pi\build\weather_routing_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\Boat.cpp(267): war
ning C4305: 'argument' : truncation from 'double' to 'float' [C:\Users\Frederic
k\Documents\GitHub\weather_routing_pi\build\weather_routing_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\RouteMapOverlay.cp
p(1235): warning C4056: overflow in floating-point constant arithmetic [C:\User
s\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_pi.vcxpro
j]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\LineBufferOverlay.
cpp(161): warning C4305: 'initializing' : truncation from 'double' to 'float' [
C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather_routing_pi
.vcxproj]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\libtess2\sweep.c(1
126): warning C4244: '=' : conversion from 'double' to 'TESSreal', possible los
s of data [C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather
_routing_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\libtess2\sweep.c(1
127): warning C4244: '=' : conversion from 'double' to 'TESSreal', possible los
s of data [C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather
_routing_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\libtess2\sweep.c(1
128): warning C4244: '=' : conversion from 'double' to 'TESSreal', possible los
s of data [C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather
_routing_pi.vcxproj]
  C:\Users\Frederick\Documents\GitHub\weather_routing_pi\src\libtess2\sweep.c(1
129): warning C4244: '=' : conversion from 'double' to 'TESSreal', possible los
s of data [C:\Users\Frederick\Documents\GitHub\weather_routing_pi\build\weather
_routing_pi.vcxproj]

    10 Warning(s)
    0 Error(s)
```

**Comment by Hakansv** [comment]
I get the impression you've built for O .4.8.8 with wx 3.0?
When I try to build for O 4.99, V5 candidate, and wx 3.1.2 in VS 2017 I still get the errors as of my initial post.
A build for wx 3.0 is OK for me as well.
Håkan

**Comment by rgleason** [comment]
Sorry should have made that clearer. Built for Windows  Opencpn v4.2.0-4.8.8  with the older version of wxwidgets.

http://www.cruisersforum.com/forums/f134/weather-routing-100060.html#post2814435

**Comment by Hakansv** [comment]
After I added some zlib-files to buildwin it now builds on VS2017 and wx3.1.2
